abbr -a -U -- rbbc 'bundle clean'
abbr -a -U -- rbbe 'bundle exec'
abbr -a -U -- rbbi 'bundle install --path vendor/bundle'
abbr -a -U -- rbbl 'bundle list'
abbr -a -U -- rbbo 'bundle open'
abbr -a -U -- rbbp 'bundle package'
abbr -a -U -- rbbu 'bundle update'