abbr -a -- rbbc 'bundle clean'
abbr -a -- rbbe 'bundle exec'
abbr -a -- rbbi 'bundle install --path vendor/bundle'
abbr -a -- rbbl 'bundle list'
abbr -a -- rbbo 'bundle open'
abbr -a -- rbbp 'bundle package'
abbr -a -- rbbu 'bundle update'
